//
//  UIColor+PPAdditions.swift
//
//  Generated by Zeplin on 10/26/17.
//  Copyright (c) 2017 papaolabs. All rights reserved. 
//

import UIKit

extension UIColor {
	@nonobjc class var warmPink: UIColor { 
		return UIColor(red: 252.0 / 255.0, green: 78.0 / 255.0, blue: 117.0 / 255.0, alpha: 1.0)
	}
}
