//
//  UIColor+PPAdditions.swift
//
//  Generated by Zeplin on 11/28/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var ppWarmPink: UIColor { 
		return UIColor(red: 252.0 / 255.0, green: 78.0 / 255.0, blue: 117.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppShadowGray: UIColor { 
		return UIColor(white: 0.0, alpha: 0.1)
	}

	@nonobjc class var ppBorderGray: UIColor { 
		return UIColor(white: 155.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppTextBlack: UIColor { 
		return UIColor(white: 3.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppHorizontalLineGray: UIColor { 
		return UIColor(red: 223.0 / 255.0, green: 220.0 / 255.0, blue: 220.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppBackgroundGray: UIColor { 
		return UIColor(white: 242.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppBrightBlue: UIColor { 
		return UIColor(red: 0.0, green: 122.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppPlaceholderGray: UIColor { 
		return UIColor(white: 216.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppBrownishGray: UIColor { 
		return UIColor(white: 101.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppDodgerBlue: UIColor { 
		return UIColor(red: 59.0 / 255.0, green: 150.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppPinkishGrey: UIColor { 
		return UIColor(white: 206.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppLightPink: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 223.0 / 255.0, blue: 234.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppDarkishPink: UIColor { 
		return UIColor(red: 227.0 / 255.0, green: 58.0 / 255.0, blue: 97.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppBabyBlue: UIColor { 
		return UIColor(red: 178.0 / 255.0, green: 218.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppDarkSkyBlue: UIColor { 
		return UIColor(red: 58.0 / 255.0, green: 147.0 / 255.0, blue: 224.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppTangerineOrange: UIColor { 
		return UIColor(red: 238.0 / 255.0, green: 124.0 / 255.0, blue: 22.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppEggShell: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 237.0 / 255.0, blue: 194.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppCoolBlue: UIColor { 
		return UIColor(red: 78.0 / 255.0, green: 178.0 / 255.0, blue: 200.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppLightSkyBlue: UIColor { 
		return UIColor(red: 201.0 / 255.0, green: 249.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppSkyBlue: UIColor { 
		return UIColor(red: 92.0 / 255.0, green: 196.0 / 255.0, blue: 248.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppPastelOrange: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 156.0 / 255.0, blue: 66.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppSeafoamBlue: UIColor { 
		return UIColor(red: 101.0 / 255.0, green: 195.0 / 255.0, blue: 215.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppPurpleyPink: UIColor { 
		return UIColor(red: 198.0 / 255.0, green: 64.0 / 255.0, blue: 202.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppPurplePink: UIColor { 
		return UIColor(red: 226.0 / 255.0, green: 89.0 / 255.0, blue: 232.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppLightTeal: UIColor { 
		return UIColor(red: 136.0 / 255.0, green: 217.0 / 255.0, blue: 227.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppWarmPinkTwo: UIColor { 
		return UIColor(red: 252.0 / 255.0, green: 92.0 / 255.0, blue: 150.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppLightGold: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 198.0 / 255.0, blue: 91.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppCarolinaBlue: UIColor { 
		return UIColor(red: 138.0 / 255.0, green: 200.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppBarney: UIColor { 
		return UIColor(red: 180.0 / 255.0, green: 40.0 / 255.0, blue: 185.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var ppLavenderPink: UIColor { 
		return UIColor(red: 230.0 / 255.0, green: 150.0 / 255.0, blue: 233.0 / 255.0, alpha: 1.0)
	}
}
